//Changes the paragraph with id of 'fill' with a string of text according what the webpage vistor enters
function myFunction() {
    var text;
    var fruits = document.getElementById("myInput").value;
  // switch statement controls what the paragraph with id of 'fill' says.
    switch(fruits) {
      case "Flowers":
        text = "Flowers are a beautiful choice! " + candies[0];
    //break exits a switch statement
      break;
    //using "case" to make lowercase and uppercase answers valid
      case "flowers":
    /*array incorporated into switch statements.  candies [0,1,2,3]strings are joined to the text string.*/
        text = "Flowers are a beautiful choice! " + candies[0];
      break;
      case "Candy":
      text = "Excellent choice. " + candies[1];
      break;
      case "candy":
      text = "Excellent choice. " + candies[1];
      break;
      case "Card":
      text = "Easy.";
      break;
      case "card":
      text = "Easy.";
      break;
      case "All of these":
      text = "You go!" + candies[2];
      break;
      case "all of these":
      text = "You go! " + candies[2];
      break;
      default:
      text = "WHAT!?!? " + candies[3];
    }
    //Puts switch text into the paragraph with id 'fill'.
    document.getElementById("fill").innerHTML = text;
    
  }
  //javascript array, used in the above function myFunction()
  // Adds the string of text to the switch text.
  const candies = ["Chocolate roses would be nice.", "Conversation Hearts might be delicious", "Make sure you get alot of chocolate!", "I hope you get something."];
//This function does not use an argument.
  function Clickhere() {

    // dynamically create a div
    const node = document.createElement("div");
    
    // Create a text node:
    var newText = document.getElementById("Input").value;
    const textnode = document.createTextNode(newText);
    
    // Append the text node to the "li" node:
    node.appendChild(textnode);
    
    // Append the "div" node to the list:
    document.getElementById("myList").appendChild(node);
    }
    //variable integrated using tick marks
    let text1 = `I hate Valentine's Day!`;
    //Dynamically repeating a string of text
    let result = text1.repeat(150);

  //dynamically filling an element by using the getElementById()

    document.getElementById("Ihate").innerHTML = result;
//Use of incremented and decremented variables
// Select increment and decrement buttons
const incrementCount = document.getElementById("increment-count");
const decrementCount = document.getElementById("decrement-count");

// Select total count
const totalCount = document.getElementById("total-count");

// Variable to track count
var count = 0;

// Display initial count value
totalCount.innerHTML = count;

// Function to increment count
const handleIncrement = () => {
  count++;
  totalCount.innerHTML = count;
};

// Function to decrement count
const handleDecrement = () => {
  count--;
  totalCount.innerHTML = count;
};

//eventlistener
// Add click event to buttons

incrementCount.addEventListener("click", handleIncrement);
decrementCount.addEventListener("click", handleDecrement);

//change CSS color of text from black to red using javascript 
function mouseOver() {
    document.getElementById("mouse").style.color = "red";
  }
  
  function mouseOut() {
    document.getElementById("mouse").style.color = "black";
  }
  //remove an element using javascript
  function removeHandler() {
    var myobj = document.getElementById("repeat");
    myobj.remove();
  }

  //function that uses arguments
  function howMuch(a, b) {
    return a * b;
  }
  document.getElementById("much").innerHTML = howMuch(
    10,
    98765432198765432198765432198765432123456789
  );
  //use of CSS selectors applied to HTML generated by Javascript
  document.getElementById("p2").style.color = "purple";
  document.getElementById("p2").style.fontFamily = "Arial";
  document.getElementById("p2").style.fontSize = "larger";
  //use of Date()
  const d = new Date();
  let text = d.toDateString();
  document.getElementById("dat").innerHTML = text  
  
  //countdown timer using math.floor (standard built in objects in javascript)


// Set the date we're counting down to
var countDownDate = new Date("Feb 14, 2023 ").getTime();
// Update the count down every 1 second
var x = setInterval(function () {
  // Get today's date and time
  var now = new Date().getTime();
  // Find the distance between now and the count down date
  var distance = countDownDate - now;
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML =
   "You have " + days + " d " + hours + " h " + minutes + " m " + seconds + " s until the next Valentine's Day. Be ready!";
  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "You are to LATE!";
  }
}, 1000);